-- ============================================================
-- Sistema de Reposição de Aulas
-- ============================================================
-- Rode este arquivo inteiro uma vez no Supabase: painel do projeto →
-- SQL Editor → New query → cole tudo → Run.
--
-- O que ele cria:
--   1) tabela `reposicoes`       — um "caso" de reposição (1 aluno + 1 aula perdida)
--   2) tabela `reposicao_opcoes` — as datas/turmas oferecidas para aquele caso
--   3) RLS: a equipe (autenticada) tem acesso total às duas tabelas, exatamente
--      como já acontece hoje com turmas/alunos/presenças. O público (não
--      autenticado) NÃO tem nenhum acesso direto às tabelas — só pode ler e
--      escrever através das duas funções no final do arquivo, que validam o
--      token antes de fazer qualquer coisa. É assim que a página pública
--      (reposicao.html) consegue funcionar sem login.
--   4) Realtime na tabela `reposicoes`, para o painel avisar a equipe na hora
--      quando um aluno confirma um horário.
--
-- O script é seguro para rodar mais de uma vez (usa `if not exists` /
-- `create or replace` / checagens antes de cada `alter`).
-- ============================================================

-- ---------- 1) Tabelas ----------

create table if not exists reposicoes (
  id                bigint generated by default as identity primary key,
  aluno_id          bigint not null references alunos(id),
  turma_origem_id   bigint not null references turmas(id),
  aula              text not null,
  status            text not null default 'aberta'
                       check (status in ('aberta','agendada','concluida','cancelada')),
  token             text not null unique default gen_random_uuid()::text,
  opcao_escolhida_id bigint,
  criado_por        bigint references professores(id),
  created_at        timestamptz not null default now(),
  confirmado_em     timestamptz
);

create table if not exists reposicao_opcoes (
  id                bigint generated by default as identity primary key,
  reposicao_id      bigint not null references reposicoes(id) on delete cascade,
  turma_destino_id  bigint not null references turmas(id),
  data              date not null,
  observacao        text,
  created_at        timestamptz not null default now()
);

-- FK circular (reposicoes.opcao_escolhida_id -> reposicao_opcoes.id) só pode
-- ser criada depois que as duas tabelas já existem.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'reposicoes_opcao_escolhida_fk'
  ) then
    alter table reposicoes
      add constraint reposicoes_opcao_escolhida_fk
      foreign key (opcao_escolhida_id) references reposicao_opcoes(id);
  end if;
end $$;

create index if not exists idx_reposicao_opcoes_reposicao_id on reposicao_opcoes(reposicao_id);
create index if not exists idx_reposicoes_aluno_id on reposicoes(aluno_id);

-- ---------- 2) RLS ----------

alter table reposicoes enable row level security;
alter table reposicao_opcoes enable row level security;

-- Equipe logada (professores/admin): acesso total, no mesmo nível que as
-- demais tabelas do sistema hoje (a separação admin/professor é feita na
-- interface, não no banco — ver ARQUITETURA.md seção 15).
drop policy if exists staff_full_access on reposicoes;
create policy staff_full_access on reposicoes
  for all to authenticated using (true) with check (true);

drop policy if exists staff_full_access on reposicao_opcoes;
create policy staff_full_access on reposicao_opcoes
  for all to authenticated using (true) with check (true);

-- Público (anon): nenhuma policy = nenhum acesso direto às tabelas.
-- Todo acesso público passa pelas funções abaixo.

-- ---------- 3) Funções públicas (chamadas pela página reposicao.html) ----------

-- Devolve os dados do caso de reposição a partir do token do link — só os
-- campos necessários para a tela pública, nunca a tabela inteira.
create or replace function reposicao_publica_get(p_token text)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rep reposicoes%rowtype;
  v_result json;
begin
  select * into v_rep from reposicoes where token = p_token;
  if not found then
    return json_build_object('erro', 'nao_encontrado');
  end if;

  select json_build_object(
    'status', v_rep.status,
    'aluno_nome', a.nome,
    'aula', v_rep.aula,
    'turma_origem', t.turma,
    'curso', t.curso,
    'opcao_escolhida_id', v_rep.opcao_escolhida_id,
    'opcoes', coalesce((
      select json_agg(json_build_object(
        'id', o.id,
        'turma', td.turma,
        'professor', td.professor,
        'horario', td.horario_inicio,
        'data', o.data,
        'observacao', o.observacao
      ) order by o.data)
      from reposicao_opcoes o
      join turmas td on td.id = o.turma_destino_id
      where o.reposicao_id = v_rep.id
    ), '[]'::json)
  ) into v_result
  from alunos a
  join turmas t on t.id = v_rep.turma_origem_id
  where a.id = v_rep.aluno_id;

  return v_result;
end;
$$;

grant execute on function reposicao_publica_get(text) to anon;

-- Confirma a escolha de uma opção. Só funciona se o caso ainda estiver
-- "aberta" e a opção pertencer a esse mesmo caso — o "where status='aberta'"
-- no update, combinado com o retorno de linhas afetadas, evita que dois
-- cliques simultâneos (ex.: duas abas do mesmo link) confirmem duas opções
-- diferentes para o mesmo caso.
create or replace function reposicao_publica_confirmar(p_token text, p_opcao_id bigint)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rep_id bigint;
  v_opcao_rep_id bigint;
  v_updated int;
begin
  select id into v_rep_id from reposicoes where token = p_token and status = 'aberta';
  if v_rep_id is null then
    return json_build_object('erro', 'indisponivel');
  end if;

  select reposicao_id into v_opcao_rep_id from reposicao_opcoes where id = p_opcao_id;
  if v_opcao_rep_id is null or v_opcao_rep_id <> v_rep_id then
    return json_build_object('erro', 'opcao_invalida');
  end if;

  update reposicoes
    set status = 'agendada', opcao_escolhida_id = p_opcao_id, confirmado_em = now()
    where id = v_rep_id and status = 'aberta';

  get diagnostics v_updated = row_count;
  if v_updated = 0 then
    return json_build_object('erro', 'ja_confirmado');
  end if;

  return json_build_object('ok', true);
end;
$$;

grant execute on function reposicao_publica_confirmar(text, bigint) to anon;

-- ---------- 4) Realtime ----------
-- Permite que o painel autenticado escute em tempo real quando um aluno
-- confirma um horário (para mostrar o aviso na hora, sem precisar recarregar
-- a aba "Reposições"). Equivalente a ligar o toggle em Database → Replication
-- para a tabela `reposicoes`, só que via SQL.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'reposicoes'
  ) then
    alter publication supabase_realtime add table reposicoes;
  end if;
end $$;
